# Generated by Django 5.2.8 on 2026-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=128, null=True, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="OTP",
        ),
    ]
