# Generated by Django 5.2.8 on 2026-06-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone_number_delete_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_phone_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
