# Generated by Django 5.2.8 on 2026-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShadowLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("django_response", models.JSONField(blank=True, null=True)),
                ("playnest_response", models.JSONField(blank=True, null=True)),
                ("django_status_code", models.IntegerField()),
                ("playnest_status_code", models.IntegerField(blank=True, null=True)),
                ("diff_result", models.JSONField(blank=True, null=True)),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("MATCH", "Match"),
                            ("MISMATCH", "Mismatch"),
                            ("ERROR", "Error"),
                        ],
                        default="MATCH",
                        max_length=20,
                    ),
                ),
                (
                    "mismatch_severity",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("django_latency_ms", models.FloatField()),
                ("playnest_latency_ms", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
