# Generated by Django 5.2.8 on 2026-06-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
    ]
