# Generated by Django 5.2.8 on 2026-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_alter_comment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time the record was created.",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Specifies whether this record is active or not.",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time of the last update to the record.",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time the record was created.",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Specifies whether this record is active or not.",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time of the last update to the record.",
                verbose_name="Updated At",
            ),
        ),
    ]
