version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: playenest-dev
      POSTGRES_PASSWORD: playenest-dev-password
      POSTGRES_DB: playenest-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
