# Generated by Django 5.2.8 on 2026-06-09 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medias", "0001_initial"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmedia",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_attachments",
                to="posts.post",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postmedia",
            unique_together={("post", "media", "attachment_type")},
        ),
    ]
