"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv
from kombu import Exchange, Queue

# EN: Build paths inside the project like this: BASE_DIR / 'subdir'.
# FA: ساخت مسیرها در داخل پروژه به این صورت: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# EN: Load environment variables from .env file.
# FA: بارگذاری متغیرهای محیطی از فایل .env.
load_dotenv(BASE_DIR / ".env")

# EN: Flag to detect if the current process is a management command.
# FA: پرچمی برای تشخیص اینکه آیا فرآیند فعلی یک دستور مدیریتی است یا خیر.
IS_MANAGEMENT_COMMAND = "manage.py" in sys.argv[0]

# EN: Create logs directory for centralized application logging.
# FA: ایجاد دایرکتوری لاگ‌ها برای ثبت متمرکز لاگ‌های اپلیکیشن.
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)


# EN: Quick-start development settings - unsuitable for production
# EN: See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
# FA: تنظیمات سریع برای محیط توسعه - نامناسب برای محیط تولید.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "replace-this-with-a-very-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "t")

# EN: Site identity and connectivity configuration.
# FA: تنظیمات هویت سایت و پیکربندی اتصال.
DOMAIN = os.environ.get("DOMAIN", "localhost")
USE_CDN = os.environ.get("USE_CDN", "False").lower() in ("true", "1", "t")
CDN_DOMAIN = os.environ.get("CDN_DOMAIN", "")
STATIC_API_KEY = os.environ.get("STATIC_API_KEY")
SITE_NAME = os.environ.get("SITE_NAME", "Blog Platform")
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", f"localhost,127.0.0.1,{DOMAIN}").split(
    ","
)


# EN: Application definition - core, third-party, and project-specific apps.
# FA: تعریف اپلیکیشن - اپلیکیشن‌های اصلی، شخص ثالث و اختصاصی پروژه.

INSTALLED_APPS = [
    "django_ckeditor_5",
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "rest_framework",
    "channels",
    "django_filters",
    "drf_spectacular",  # Required for drf-spectacular
    "users",
    "common",
    "corsheaders",
    "axes",
    "django_celery_results",
    "djoser",
    "sslserver",
    "guardian",
    "simple_history",
    "import_export",
    "silk",
    "django_select2",
    "jalali_date",
    "tempus_dominus",
    "formtools",
    "core",
    "posts",
    "medias",
    "interactions",
    "pages",
    "navigation",
]

# EN: Authentication backends including support for object permissions (guardian) and lockout protection (axes).
# FA: بک‌اندهای احراز هویت شامل پشتیبانی از دسترسی‌های سطح شیء (guardian) و محافظت در برابر مسدود شدن (axes).
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "blog.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "blog.wsgi.application"
ASGI_APPLICATION = "blog.asgi.application"

# EN: Database configuration with support for environment-driven URLs and SQLite fallback for tests.
# FA: تنظیمات پایگاه داده با پشتیبانی از آدرس‌های مبتنی بر محیط و جایگزین SQLite برای تست‌ها.
is_testing_db = "test" in sys.argv or "pytest" in sys.modules

if is_testing_db:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
else:
    DATABASE_URL = os.environ.get("DATABASE_URL")
    if DATABASE_URL:
        DATABASES = {"default": dj_database_url.config(default=DATABASE_URL)}
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 12,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# EN: Internationalization settings. Timezone is UTC for global consistency.
# FA: تنظیمات بین‌المللی‌سازی. منطقه زمانی برای یکپارچگی جهانی روی UTC تنظیم شده است.
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# EN: Static and Media files configuration. Uses WhiteNoise for static files and local/S3 for media.
# FA: تنظیمات فایل‌های ایستا و رسانه‌ای. استفاده از WhiteNoise برای فایل‌های ایستا و فضای محلی/S3 برای رسانه‌ها.
if USE_CDN and CDN_DOMAIN:
    STATIC_URL = f"https://{CDN_DOMAIN}/static/"
else:
    STATIC_URL = "/static/"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

if USE_CDN and CDN_DOMAIN:
    MEDIA_URL = f"https://{CDN_DOMAIN}/media/"
else:
    MEDIA_URL = os.environ.get("MEDIA_URL", "/media/")

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
PRIVATE_MEDIA_ROOT = os.path.join(BASE_DIR, "private_media")

# Custom Storage Settings
STORAGE_BACKEND = os.environ.get("STORAGE_BACKEND", "local")

if STORAGE_BACKEND == "s3":
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME")
    AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL")
    AWS_S3_CUSTOM_DOMAIN = os.environ.get("AWS_S3_CUSTOM_DOMAIN")

    if not AWS_S3_CUSTOM_DOMAIN:
        if AWS_S3_ENDPOINT_URL:
            # EN: Extract domain from endpoint URL if custom domain is not provided.
            # FA: استخراج دامنه از آدرس اندپوینت در صورتی که دامنه سفارشی ارائه نشده باشد.
            AWS_S3_CUSTOM_DOMAIN = (
                AWS_S3_ENDPOINT_URL.split("//")[-1].rstrip("/")
                + f"/{AWS_STORAGE_BUCKET_NAME}"
            )
        else:
            AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }
    AWS_LOCATION = "media"

    if not (USE_CDN and CDN_DOMAIN):
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/"
else:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# EN: Custom user model to allow for future profile extensions.
# FA: مدل کاربر سفارشی برای اجازه دادن به گسترش‌های پروفایل در آینده.
AUTH_USER_MODEL = "users.User"

# EN: Redis and Channels configuration for real-time features and caching.
# FA: تنظیمات Redis و Channels برای ویژگی‌های بلادرنگ و کشینگ.
REDIS_URL = os.environ.get("REDIS_URL")
USE_REDIS = (
    os.environ.get("USE_REDIS", "false").lower() in ("true", "1", "t") and REDIS_URL
)

if "test" in sys.argv or not USE_REDIS:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }

# EN: Logging Configuration for detailed error tracking and performance monitoring.
# FA: تنظیمات لاگ برای ردیابی دقیق خطاها و نظارت بر کارایی.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
        "json": {
            "class": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(name)s %(levelname)s %(module)s %(lineno)d %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file_info": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/app.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 2,
            "formatter": "verbose",
        },
        "file_error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/error.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 2,
            "formatter": "json",
        },
        "smtp_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/smtp.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 2,
            "formatter": "verbose",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": True,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file_info", "file_error"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["mail_admins", "file_error"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.core.mail": {
            "handlers": ["smtp_file"],
            "level": "INFO",
            "propagate": True,
        },
        "root": {
            "handlers": ["console", "file_info", "file_error"],
            "level": "INFO",
        },
    },
}

# EN: Use console logging in development and file/email logging in production.
# FA: استفاده از لاگ کنسول در توسعه و لاگ فایل/ایمیل در تولید.
if DEBUG or "test" in sys.argv or "pytest" in sys.modules:
    LOGGING["loggers"]["django"]["handlers"] = ["console"]
    LOGGING["loggers"]["root"]["handlers"] = ["console"]
else:
    LOGGING["loggers"]["django"]["handlers"] = ["file_info", "file_error"]
    LOGGING["loggers"]["django"]["propagate"] = False
    LOGGING["loggers"]["root"]["handlers"] = ["file_info", "file_error", "mail_admins"]


# EN: Unfold Admin Theme configuration.
# FA: تنظیمات قالب Unfold برای پنل ادمین.
UNFOLD = {
    "SITE_HEADER": "Blog Platform",
    "SITE_TITLE": "Blog Platform Admin",
    "SITE_URL": "/",
    "THEME": "dark",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
    },
}

# EN: Django REST Framework Settings with standardized response and schema generation.
# FA: تنظیمات Django REST Framework با تولید پاسخ و شمای استاندارد.
REST_FRAMEWORK = {
    # This line is required for drf-spectacular
    "DEFAULT_SCHEMA_CLASS": "common.schema.StandardizedAutoSchema",
    # This line is for using Static API Key Authentication
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "common.authentication.StaticAPIKeyAuthentication",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "common.renderers.StandardResponseRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "EXCEPTION_HANDLER": "common.exceptions.custom_exception_handler",
}

# EN: Spectacular settings for OpenAPI documentation generation.
# FA: تنظیمات Spectacular برای تولید مستندات OpenAPI.
SPECTACULAR_SETTINGS = {
    "TITLE": f"{SITE_NAME} API",
    "DESCRIPTION": "API for managing posts, medias, interactions, pages, navigation and users.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api",
    "CONTACT": {
        "name": "Admin",
        "url": "https://example.com",
        "email": "admin@example.com",
    },
    "LICENSE": {
        "name": "MIT License",
    },
    "COMPONENT_SPLIT_PATCH": True,
    "COMPONENT_SPLIT_REQUEST": True,
    "ENUM_NAME_OVERRIDES": {
        "PostStatusEnum": "posts.models.Post.STATUS_CHOICES",
        "CommentStatusEnum": "interactions.models.Comment.STATUS_CHOICES",
    },
}

# EN: Djoser configuration for authentication and account management.
# FA: تنظیمات Djoser برای احراز هویت و مدیریت حساب کاربری.
DJOSER = {
    "PASSWORD_RESET_CONFIRM_URL": f"{FRONTEND_URL}/#/password/reset/confirm/{{uid}}/{{token}}",
    "USERNAME_RESET_CONFIRM_URL": f"{FRONTEND_URL}/#/username/reset/confirm/{{uid}}/{{token}}",
    "ACTIVATION_URL": f"{FRONTEND_URL}/#/activate/{{uid}}/{{token}}",
    "SEND_ACTIVATION_EMAIL": True,
    "USER_CREATE_PASSWORD_RETYPE": True,
    "PASSWORD_CHANGED_EMAIL_CONFIRMATION": True,
    "USERNAME_CHANGED_EMAIL_CONFIRMATION": True,
    "PASSWORD_RESET_CONFIRM_RETYPE": True,
    "SET_USERNAME_RETYPE": True,
    "SET_PASSWORD_RETYPE": True,
    "SERIALIZERS": {},
    "SITE_NAME": SITE_NAME,
}


FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]

# EN: Security headers and cookie protection.
# FA: هدرهای امنیتی و محافظت از کوکی‌ها.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "SAMEORIGIN"
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# EN: Force HTTPS in production environments.
# FA: اجبار استفاده از HTTPS در محیط‌های تولید.
is_testing = "test" in sys.argv or "pytest" in sys.modules

SECURE_SSL_REDIRECT = not DEBUG and not is_testing
# In production, use secure cookies.
SESSION_COOKIE_SECURE = not DEBUG and not is_testing
CSRF_COOKIE_SECURE = not DEBUG and not is_testing

if not DEBUG and not is_testing:
    MIDDLEWARE.insert(2, "silk.middleware.SilkyMiddleware")

CORS_ALLOWED_ORIGINS = [
    origin for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") if origin
]

if DEBUG:
    CORS_ALLOWED_ORIGINS.extend(
        [
            "http://127.0.0.1:5501",
            "http://localhost:5501",
        ]
    )

CORS_ALLOW_ALL_ORIGINS = os.environ.get("CORS_ALLOW_ALL_ORIGINS", "False").lower() in (
    "true",
    "1",
    "t",
)

# EN: Axes configuration for brute-force protection.
# FA: تنظیمات Axes برای محافظت در برابر حملات brute-force.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1
AXES_RESET_ON_SUCCESS = True
AXES_NEVER_LOCKOUT_CALLABLE = "users.auth_utils.should_never_lockout_staff"

# EN: Celery configuration for background tasks and scheduled events.
# FA: تنظیمات Celery برای تسک‌های پس‌زمینه و رویدادهای زمان‌بندی شده.
if USE_REDIS:
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL
else:
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache+memory://"

CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_QUEUES = (
    Queue("high_priority", Exchange("high_priority"), routing_key="high_priority"),
    Queue("default", Exchange("default"), routing_key="default"),
    Queue("low_priority", Exchange("low_priority"), routing_key="low_priority"),
)
CELERY_TASK_ROUTES = {}
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_ACKS_ON_FAILURE_OR_TIMEOUT = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(
    os.environ.get("CELERY_WORKER_MAX_TASKS_PER_CHILD", "100")
)
CELERY_TASK_SOFT_TIME_LIMIT = int(os.environ.get("CELERY_TASK_SOFT_TIME_LIMIT", "900"))
CELERY_TASK_TIME_LIMIT = int(os.environ.get("CELERY_TASK_TIME_LIMIT", "960"))
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": int(os.environ.get("CELERY_VISIBILITY_TIMEOUT", "1200"))
}
CELERY_RESULT_EXPIRES = timedelta(
    hours=int(os.environ.get("CELERY_RESULT_EXPIRES_HOURS", "24"))
)

CELERY_BEAT_SCHEDULE = {
    "publish-scheduled-posts": {
        "task": "posts.tasks.publish_scheduled_posts_task",
        "schedule": timedelta(minutes=1),
    },
}

if "test" in sys.argv or "pytest" in sys.modules:
    CELERY_TASK_ALWAYS_EAGER = True
    # Disable guardian's anonymous user during tests to prevent test failures
    ANONYMOUS_USER_NAME = None

# EN: Email Configuration for outgoing system messages.
# FA: تنظیمات ایمیل برای پیام‌های خروجی سیستم.
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() in ("true", "1", "t")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "webmaster@localhost")

CSRF_TRUSTED_ORIGINS = [
    origin for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if origin
]


if "test" in sys.argv or "pytest" in sys.modules or not USE_REDIS:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": f"{REDIS_URL}/1",  # DB 1 for cache, 0 for channels/celery
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        },
    }

# EN: CKEditor 5 configuration for rich text editing.
# FA: تنظیمات CKEditor 5 برای ویرایش متن غنی (Rich Text).
CKEDITOR_5_UPLOAD_PATH = "uploads/"
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "link",
            "bulletedList",
            "numberedList",
            "outdent",
            "indent",
            "blockQuote",
            "insertTable",
            "imageUpload",
            "mediaEmbed",
            "undo",
            "redo",
        ],
        "uploadUrl": "/api/editor/upload/",
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "imageStyle:inline",
                "imageStyle:block",
                "imageStyle:side",
            ]
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
            ]
        },
        "mediaEmbed": {"previewsInData": True},
        "link": {"addTargetToExternalLinks": True},
    }
}

# EN: Enable automatic Jalali conversion for admin list displays.
# FA: فعال‌سازی تبدیل خودکار جلالی برای نمایش‌های لیست در پنل ادمین.
JALALI_DATE_DEFAULTS = {"LIST_DISPLAY_AUTO_CONVERT": True}
