name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install black isort flake8
      - name: Run Black
        run: black --check .
      - name: Run isort
        run: isort --check-only .
      - name: Run Flake8
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: PlayNest/package-lock.json
      - name: Install dependencies
        run: |
          cd PlayNest
          npm install
      - name: Run PlayNest Tests
        run: |
          cd PlayNest
          npm test
